---
- hosts: master
  vars_files:
    - secrets.yml
  tags: master
  gather_facts: false
  roles:
  - master
  vars:
    ipv6_subnet: "{{vault_ipv6_subnet}}"
    ipv6_bridge_address: "{{ipv6_subnet}}:c:c:c:1"
    ipv6_interface: "{{vault_ipv6_interface}}"
    blocks_directory: "{{vault_blocks_directory}}"
    ssh_public_key: "{{vault_ssh_public_key}}"
- hosts: nodes
  vars_files:
    - secrets.yml
  tags: nodes
  roles:
  - nodes
  vars:
    ipv6_subnet: "{{vault_ipv6_subnet}}"
    ipv6_bridge_address: "{{ipv6_subnet}}:c:c:c:1"
- hosts: monitoring
  tags: monitoring
  vars_files:
    - secrets.yml
  vars:
    monitoring_enabled: true
  roles:
  - monitoring
