---
- hosts: master
  tags: master
  roles:
  - ansible-hardening
  - master
#- hosts: supernodes
#  tags: nodes
#  roles:
#  - nodes
- hosts: nodes
  tags: nodes
  roles:
  - nodes
- hosts: monitoring
  tags: monitoring
  roles:
  - monitoring
