---
- hosts: master
  vars_files:
    - secrets.yml
  gather_facts: false
  tasks:
    - name: Start ssh server
      shell: lxc-attach -n {{vault_nodes[item].ansible_fqdn}} -- systemctl start ssh
      with_items: "{{ groups['nodes'] | union(groups['monitoring'])}}"
