---
- hosts: master
  gather_facts: false
  become: true
  tasks:
    - name: Stop secure node ssh servers
      shell: lxc-attach -n {{hostvars[item].ansible_fqdn}} -- systemctl stop ssh
      with_items: "{{ groups['securenodes'] }}"
      when: groups['securenodes'] is defined
    - name: Stop super node ssh servers
      shell: lxc-attach -n {{hostvars[item].ansible_fqdn}} -- systemctl stop ssh
      with_items: "{{ groups['supernodes'] }}"
      when: groups['supernodes'] is defined
