---
# TODO: this playbook will update the seed on the master with one on the first secure node. Will cause a few minutes of downtime.

- hosts: master
  vars_files:
    - secrets.yml
  gather_facts: false
  tasks:
    - name: Stop secure node ssh servers
      shell: lxc-attach -n {{vault_nodes[item].ansible_fqdn}} -- systemctl stop ssh
      with_items: "{{ groups['nodes'] }}"
      when: groups['nodes'] is defined
    - name: Stop super node ssh servers
      shell: lxc-attach -n {{vault_nodes[item].ansible_fqdn}} -- systemctl stop ssh
      with_items: "{{ groups['supernodes'] }}"
      when: groups['supernodes'] is defined
    - name: Stop monitoring node ssh server
      shell: lxc-attach -n {{vault_monitoring.ansible_fqdn}} -- systemctl stop ssh
      when: groups['monitoring'] is defined
