---
- include_tasks: gather-vars.yml
  tags: gather-vars
- include_tasks: ssh.yml
  tags:  ssh
- include_tasks: ssl.yml
  tags: ssl
- include_tasks: zend.yml
  tags: zend
- include_tasks: rsyslog.yml
  tags: rsyslog
- include_tasks: node.yml
  tags: node
- include_tasks: nodetracker.yml
  tags: nodetracker
