---
- name: Install prerequisites
  apt:
    name: ca-certificates
    state: latest

- name: install grafana key
  apt_key:
    url: https://packagecloud.io/gpg.key
    state: present

- name: Install grafana repo
  apt_repository:
    repo: "deb https://packagecloud.io/grafana/stable/debian/ stretch main"
    state: present

- name: Install grafana
  apt:
    name: grafana
    state: latest

- name: Start and enable grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes
